### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rohit1290** [manlui/elgg_with_rest_api#1]
1. Why have you uploaded the entire elgg folder when you are just editing web_services folder. People have to download the entire elgg setup just to get that one folder.
2. Why are you editing the core files? Once a new version of elgg is available like 1.12.x to 1.12.y the entire folder will be replaced with the original core source code and people using this will have to again upload your code. This will be very complicated to maintain.

**Comment by manlui** [comment]
thanks I will just keep the web_services folder only.

**Comment by rohit1290** [comment]
Is this finalized? can I use it on my server?

**Comment by rohit1290** [comment]
In the readme file its written elgg 1.0-1.8 but in the mainfest file its mentioned elgg release 1.9. Which one is correct?

**Comment by manlui** [comment]
No, is not finalized, I still adding features to it. I test it on 1.10, but I think will work on >= 1.9.

**Comment by rohit1290** [comment]
I was following your instruction file
https://docs.google.com/document/d/1ZJEEu5otdpjHVPNc0au9tbaUTY9jzB3CBEGfzYYUQpo/edit

There is no instruction on how to obtain the Google API Key?
What services to select. How to get the API key?

**Comment by rohit1290** [comment]
and 2nd things was, by what time will this app be ready to use. Even I want to use the app for my user. This is going to be awesome. Thank you for your hard work.

**Comment by manlui** [comment]
Yes, you can create a Google API Key in link: https://developers.google.com/cloud-messaging/android/client
This is for Google Cloud Messaging, if you following following their instruction it will enable the right service for you. Is not a require thing for the app to work, only if you want to see the push notification on your phone for the message.

You will also need to edit the file in: mod/messages/start.php
on line 320 add following line 
push_notification_message($sender->name, $sender->username, $recipient->name, $recipient->username, $message_sent->title, $message_sent->description);

then also add the following function on the the bottom of that page.

//send gcm to phone
function push_notification_message($sender_name, $sender_username, $recipient_name, $recipient_username, $message_sent_title, $message_sent_description)
{
    $path = elgg_get_plugins_path();
    include_once $path.'web_services/lib/GCM.php';
    $gcm = new GCM();
    $result = $gcm->setup_message($sender_name, $sender_username, $recipient_name, $recipient_username, $message_sent_title, $message_sent_description);
    if ($result) {
        echo "Message success sent";
    } else {
        echo "Fail send message";
    }
}

![msg](https://cloud.githubusercontent.com/assets/5414849/12981094/76cc967c-d09c-11e5-8918-6a2386b88923.png)

**Comment by manlui** [comment]
I think you can start using it now. The only feature it may still need to update the api call is to for adding a album view. All other api call I will not making a lot of change to it.

**Comment by rohit1290** [comment]
As you mentioned that I need to edit the start.php file of messages plugin for push notification but I am not very comfortable with that idea. If I change any core source code then all of these will be changed back to original source code if someone update their elgg version. The modified file will be simply replaced by elgg original file. So to over come that problem I have done some tweet on web services start.php file.

View changes here: https://github.com/rohit1290/elgg_with_rest_api/commit/b967951c0256ebbe541cf058fb85fcb8cdce93a4

But the problem is that I haven't tested it. I don't have a test instance. All I have is a live website and I don't want to use it for testing purpose. Do you have a testing server? Would you be able to test the code? If the code works then I will create a pull request for you so that you can merge the changes to your repository as well.
