### ISSUE TITLE
Register user requires api_auth and user_auth. How to do that?

### ISSUE THREAD

**Issue by rohit1290** [manlui/elgg_with_rest_api#12]
user.register: {
      "description": "Register user",
      "function": "user_register",
      "parameters": {
        "name": {
          "type": "string",
          "required": true
        },
        "email": {
          "type": "string",
          "required": true
        },
        "username": {
          "type": "string",
          "required": true
        },
        "password": {
          "type": "string",
          "required": true
        }
      },
      "call_method": "GET",
      "require_api_auth": true,
      "require_user_auth": true
    },

when i am thinking of signing up from the app, i assume that i will have to call user.register... however it says it requires both api_auth and user_auth.... the thing is if i am using the app for the first time and want to register for the site, how will i have both api_auth and user_auth?? because i can get api_auth and user_auth only after providing a valid username and password using auth.gettoken

**Comment by manlui** [comment]
what version of elgg you are running it in?

**Comment by rohit1290** [comment]
Elgg 1.12.12

**Comment by manlui** [comment]
I update it with false.
