### ISSUE TITLE
Improvement and Bugs in Mobile Application 

### ISSUE THREAD

**Issue by rohit1290** [manlui/elgg_with_rest_api#4]
I did a test on the Mobile app and following are some points that I think would be great for user experience and alos some bugs that I have noticed:
1. Improvement: Login page should have a better background that would be more easy on the eyes. Like now the background colour and the text box's text colour are dark making it hard to view. How about a light colour background with dark colour text.
2. Improvement: Once I reach the bottom of the home page, its taking some time to load more content. How about adding a loading gif to the bottom so that user would know that there are more feeds that is being loaded.
3. Improvement: There should be 3 tab in home page ("Friends", "Mine" and "All") just like its there in elgg and the default tab should be on "Friends" tabs.
4. Improvement: On the left side menu button only few default option is available like home, blog, photo and files. there are many users who uses event manger, bookmarks plugin. Is it possible to make that dynamic. I mean according to the elgg setup that is there for different admin.
5. Bug: CheckIn not working. It's showing "Success Post" but I can't see the post on my website. Also a loading gif would be great till the post is actually posted on the server.
6. Bug: Photo is not working: Same as Chekin.
7. Improvement: "Add Friend" should be "Follow"
8. Bug: Add friend button is not working once I open the user profile and click on "Add Friends". Also the image of the user (user's profile pic) would be great instead of elgg logo.
9. Improvement: Messages only show inbox. What about sent items?
10. Bug: When I visit my profile on the app. Its not showing my profile pic.
11. Improvement: No option to add new blog.
12. Improvement: No option to add new file.

**Comment by manlui** [comment]
Thanks this is great, some of the thing I can change sooner than other. 
1. yes, i will take a try to change it a bit.
2. yes, I will add a load icon on the page.
3. this I will take a look see, if I come up with a better desire.
4. it can be dynamic, I just don't have all the rest api call done. I have not touch the bookmarks yet. Still in my list of things will add.
5. yes, I got a typo on a post method, I think it got fixed on 1.6.1 of the app. If still having problem msg me or send me a login on you site to let me try to find out what may have case it. I run a few test I was able to do it on my site.
6. It should got fixed, it use same call.
7. Yes, I will change it.
8. That is only a display, show you are not a friend. I will try to change it to a button.
9. Still working on a rest api call and still have not come up with a desire for it yet.
10. this I am not sure, try a few  diff account on my phone it able to show I will look into it.
11. Still need to work on it on the rest api call and on the app.
12. Still need to work on it on the rest api call and on the app.

**Comment by rohit1290** [comment]
Point 13: In setting page. The url n api key automatically get reset to default url n api key of core. Is there a way that the url n api key get stored in the mobile and d apk file checks if the stored file exists or not. If the file exists then it will pull d url n api frm the file otherwise it will display d default value. Users cant copy paste the api everytime they need to login.

**Comment by manlui** [comment]
Is not require to enter it any more. It will get the api key from the server after the user auth with the server.
