### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rohit1290** [manlui/elgg_with_rest_api#6]
I am planning to organize a hackathon at my college using your APIs.

Just few quick questions
1. How can user login, using which api call?
2. "require_api_auth": true and "require_user_auth": true - how to use these? is there a specific parameter for this?

**Comment by manlui** [comment]
Yes, here is the way
1. You have to using **post** method to do the login with the method auth.gettoken, here is a example of it:
http://Your_server_address/services/api/rest/json/?method=auth.gettoken&username=your_username&password=your_password

you then should get some json back look something like this:
{
  "status": 0,
  "result": {
    "auth_token": "afadfadf99adf0fg9f98778adfa",
    "api_key": "afdakfljl3243fajlkfdj8982832493dsfweioruewior"
  }
}
1. the true for require_api_auth is that the call require the api_key that return from the json. The true for require_user_auth is the auth_token that return from the json. The auth_token expire default set to expire 60min (can be change). The auth_token will return diff each time make a call, api_key will be same.

**Comment by rohit1290** [comment]
Thank You!
