### ISSUE TITLE
Deprecated Functions

### ISSUE THREAD

**Issue by rohit1290** [manlui/elgg_with_rest_api#7]
I was analysing your code and noted that the following function has been deprecated since 1.8

In file: /web_services/lib/image.php
    Line 224:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 433:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/core.php
    Line 103:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/bookmark.php
    Line 256:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/wire.php
    Line 133:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 269:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/file.php
    Line 156:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 354:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 433:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/blog.php
    Line 90:    Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 411:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/album.php
    Line 130:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/user.php
    Line 57:    Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 218:   Function call: get_loggedin_user (deprecated since 1.8) Use elgg_get_logged_in_user_entity()
    Line 240:   Function call: add_to_river (deprecated since 1.9) Use elgg_create_river_item()
    Line 354:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 396:   Function call: get_user_friends_of (deprecated since 1.9) Use \ElggUser::getFriendsOf()
    Line 403:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 453:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 476:   Function call: get_loggedin_user (deprecated since 1.8) Use elgg_get_logged_in_user_entity()
    Line 484:   Function call: get_loggedin_user (deprecated since 1.8) Use elgg_get_logged_in_user_entity()
    Line 542:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

In file: /web_services/lib/message.php
    Line 24:    Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 103:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()
    Line 173:   Function call: get_entity_icon_url (deprecated since 1.8) Use $entity->getIconURL()

**Comment by manlui** [comment]
I got the fixed just need to push out the new code.
