### ISSUE TITLE
Can't log into the Core app.  Are your instructions at https://goo.gl/JR7lLS up to date?

### ISSUE THREAD

**Issue by blaber** [manlui/elgg_with_rest_api#9]
I'm running it on a Nexus 6 with Lollipop.  I give it my elgg server name and enter everything on my 2.1 server (using your latest plugin) according to the documentation and the app says it can't log me in.  I try to register and it says I need to download a browser??

The only thing that confused me in the setup was that it says "Then copy the public key" but it doesn't tell me where to paste it so I didn't do anything to it.  Am I missing something there?

**Comment by manlui** [comment]
That is older instruction, I will try to update it. Don't need to copy the public key, it will pull it after a success login. If you gave me you site and a test user, I can try to help take a look see what cause the problem.

**Comment by blaber** [comment]
That would be great!:

www.1stakes.tv
usrnam: tester
pd: testGCM

**Comment by manlui** [comment]
Can you double check on the web services to make sure it is enable? When I try the following url and I get was not found on this server. That should show list of api. http://www.1stakes.tv/services/api/rest/json/?method=system.api.list

**Comment by blaber** [comment]
Yeah I think so!?  I mean, I wouldn't have access to the settings to be
able to specify the Google API and site url logo if I didn't have it
enabled right??

**Comment by manlui** [comment]
Is in your elgg admin setting, is in step (9. Enable Elgg Plugins) on my instruction: https://goo.gl/JR7lLS

**Comment by blaber** [comment]
Yes.  Would it help if I temporarily made tester administrator for
troubleshooting?

**Comment by manlui** [comment]
yes, if you able to set it to admin permission, I will take a look at it.

**Comment by blaber** [comment]
Yes, I made that change now.  Thanks.

**Comment by manlui** [comment]
Hi Blaber, try to enter the site url in the app: http://www.1stakes.tv/site
This should allow you login, there is few more problem, you still need to add tidypic plugin. For it to post pictures.

**Comment by blaber** [comment]
Thanks Manlui, so that's the main issue!  I need to go to a concert now but
I'll try it after I get back...

**Comment by blaber** [comment]
Thanks Manlui, I am now able to access my account with the Core app!

The only thing I'm still having trouble with is getting the Android push
notification message through GCM from my Elgg server.  Did you have any
guesses about that for me to try?

**Comment by manlui** [comment]
Do you get a GCM api key from here? https://developers.google.com/cloud-messaging/android/client
Also can you check you database table, it should create a new table gcm_users.  Also will need to enable it on each user's settings, here is screen:
![image](https://cloud.githubusercontent.com/assets/5414849/15543848/b89d9868-2253-11e6-87e8-0869f4a5173e.png)

**Comment by blaber** [comment]
I do have a GCM api key (which you should be able to see in the settings
for the web services plugin) and the Site notifications have been turned on
between the two users I'm testing with.

But searching my elgg server's mysql database I cannot find any gcm_
strings.  It seems as though I have a couple problems with the plugin??

**Comment by manlui** [comment]
I found the problem, it was not the plugin. I normal custom build the apk with the GCM Sender Id on it, so I can send create a custom build with your sender id or I will try to create a way for you to add the id in the setting. I was able test it with my gcm key and my sender id on you server and it works.

**Comment by blaber** [comment]
Awesome...of course, that makes total sense!

A custom build with my sender id would be perfect...I have my own apps that
I can add the capability to if it turns out I need a lot of
customizations.  Although you'll get a lot more users of your app if you
add an entry in your app settings for it!

**Comment by manlui** [comment]
If you go update the web service api and the android app. It will gave you an setting box Next the GCM server key to enter the sender id now. The android will pull and use the send id from your server.

**Comment by blaber** [comment]
Hi Manlui,
When I generate the GCM API key and Sender ID what do I use for the package
name?  Right now I'm specifying lui.elgg.core and the GCM push
notifications are still not popping up on my Nexus 6 running your latest
core app.

**Comment by manlui** [comment]
The package name is: lui.elgg.core.service
I just try the sender id and gcm key in your server, I got error {"error":"MismatchSenderId"}

**Comment by blaber** [comment]
I added "service" at the end but the google developers console and it still
gave me the same API key and Sender ID.

Where is this error coming from?  I only enter in my sender ID once so I'm
not sure where the mismatch would be coming from??

**Comment by manlui** [comment]
Is in your Apache sever log, I enter the sender ID and your key in my sever and did few messages test and found the error on /var/log/apaches/error.log file. My sever is Ubuntu

**Comment by manlui** [comment]
Your can generatekey from here: https://developers.google.com/cloud-messaging/android/start

**Comment by blaber** [comment]
Yeah, that's where I generated the key that I'm using.  I'm curious why
you're getting a mismatched senderID message.  I don't get that in my
error.log on my ubuntu server??  Is it possible that you have your old
senderID specified somewhere else?

**Comment by manlui** [comment]
Let me clear my gcm table and retry it.

**Comment by blaber** [comment]
ok, sounds good...

**Comment by manlui** [comment]
I think is have to be your sender id or gcm Server API Key, I just put my key into your server and it works now. Can you try it, you still have to go into your user setting and enable the site notification

![image](https://cloud.githubusercontent.com/assets/5414849/15689788/d924eeda-273d-11e6-8a57-a99c12a174c8.png)

**Comment by manlui** [comment]
I clear the table and try again with that sender id and key and still getting "error":"MismatchSenderId"}

**Comment by blaber** [comment]
I didn't think it mattered but one other thing I could try is to change my
App name??  Would I specify "Core" as the app name in the Google developers
console?

**Comment by manlui** [comment]
Let me try it on a new gmail account, will update you if I found out why.

**Comment by blaber** [comment]
Ok, yeah, good idea.

**Comment by manlui** [comment]
I think it should work now, I forget to change one more place in the android app.

**Comment by blaber** [comment]
Haha, yep, works like a charm!  This is the most impressive elgg/app
integration I've seen yet.  Congratulations!
-brian
